import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css" />
      </Head>
      <h1>Test game</h1>
      <table>
        <caption>
          <h3>Chosir type de jeu</h3>
        </caption>
        <thead>
          <td>Empreineur</td>
          <td>Empreinte</td>
        </thead>
        <tbody>
          <tr>
            <td><Link href="/card/loaner">Jouer (Empreinteur)</Link></td>
            <td><Link href="/card/borrower">Jouer (Empreinte)</Link></td>
          </tr>
        </tbody>
      </table>
      <div>
        
      </div>
    </main>
  )
}
