import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image';
import { useEffect } from 'react';


export default function Home() {
  useEffect(() => {
    sessionStorage.removeItem('borrower_id');
    sessionStorage.removeItem('loaner_id');
  }, [])
  
  return (
    <main style={{textAlign:'center'}}>
      <Head>
          <title>Credit game</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.css" />
      </Head>
      <h3>{`Instructions`}</h3>
      <p>
        {`You are currently participating in an experiment in experimental economics presented in an electronic form. The experiment is repeated 5 times consecutively.`}
      </p>
      <h3>{`Steps`}</h3>
      <p>
        {`You will obtain a player status either "1" or "2" this thanks to the draw. If you got player 1 status, you start the experience first. Be attentive while handling the game. Towards the end of the game, you are asked to lend player 2 a financial sum so that he can also play his role. You have the freedom to accept or refuse this loan. If you obtained player 2 status, you will wait for player 1 to give you financial support in the form of credit. You have the freedom to repay or not the credit. In case of reimbursement, it is obvious to transfer a doubled amount.`}
      </p>
      <h3>{`Before the experience`}</h3>
      <p style={{marginBottom: '40px'}}>
        {`If you have a question do not hesitate to address it to the experimenter before the start of the experiment.`}
      </p>
      <Link href="/select"><a style={{color:'black', padding:'10px', backgroundColor: '#C0D9D9'}}>{`Start the experiment`}</a></Link>
      <div style={{display: 'flex', justifyContent:'space-between', marginTop: '48px'}}>
        <Image src="/fsjes.png" width={160} height={64} alt="asd"/>
        <Image src="/labo.png" width={160} height={64} alt="asd"/>
      </div>
    </main>
  )
}
