import Link from 'next/link';
import Head from 'next/head';
import { useEffect } from 'react';

export default function Select() {
    useEffect(() => {
        sessionStorage.removeItem('borrower_id');
        sessionStorage.removeItem('loaner_id');
    }, [])
    return (
        <main>
            <Head>
                <title>Credit game</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.css" />
            </Head>
            <h1>Credit game</h1>
            <table>
                <caption>
                <h3>Select player (Draw game)</h3>
                </caption>
                <tbody>
                    <tr>
                        <td><Link href="/card/loaner">Player 1</Link></td>
                        <td><Link href="/card/borrower">Player 2</Link></td>
                    </tr>
                </tbody>
            </table>
        </main>
    )
}